apiVersion: v1
kind: Service
metadata:
  name: javademoservice
spec:
  selector:
    app.kubernetes.io/name: Java-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
