name: Create eks cluster

on:
  workflow_dispatch:

jobs:
  Create-eks:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: printing variables
        run: echo "aws region is:${{ secrets.AWS_REGION }}"
      - name: Config AWS Creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version
      - name: Create EKS Cluster
        run: |
          eksctl create cluster \
            --name ${{secrets.CLUSTER_NAME}} \
            --region ${{secretes.AWS_REGION}} \
            --nodegroup-name linux-nodes \
            --node-type t2.micro \
            --nodes 2 \
            --nodes-min 1 \
            --nodes-max 3 \
            --managed          