name: Create eks cluster
on:
  workflow_dispatch: 

jobs:
  Create-eks:
   runs-on: ubuntu-latest
   steps:
      - name: Config AWS Creds
        uses: aws-actions/configure-aws-credentials@v3   
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version
    
